---
builds:
  - id: repogen
    goos: &goos-defs
      - linux
      - darwin
      - windows
    goarch: &goarch-defs
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    binary: repogen
    ldflags:
      - "-X main.buildVersion={{.Version}} -X main.buildCommit={{.ShortCommit}}"

archives:
  - id: repogen
    builds:
      - repogen
    name_template: "demo-app_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch