// Code generated by qtc from "alter_table.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../infrastructure/db/migrate/alter_table.qtpl:1
package migrate

//line ../../infrastructure/db/migrate/alter_table.qtpl:1
import (
	"github.com/Alexandrhub/cli-orm-gen/infrastructure/db/scanner"
)

//line ../../infrastructure/db/migrate/alter_table.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../infrastructure/db/migrate/alter_table.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../infrastructure/db/migrate/alter_table.qtpl:5
func StreamAlterTable(qw422016 *qt422016.Writer, field scanner.Field) {
//line ../../infrastructure/db/migrate/alter_table.qtpl:5
	qw422016.N().S(`
alter table `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:6
	qw422016.E().S(field.Table.Name)
//line ../../infrastructure/db/migrate/alter_table.qtpl:6
	qw422016.N().S(`
	add `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:7
	qw422016.E().S(field.Name)
//line ../../infrastructure/db/migrate/alter_table.qtpl:7
	qw422016.N().S(` `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:7
	qw422016.E().S(field.Type)
//line ../../infrastructure/db/migrate/alter_table.qtpl:7
	qw422016.N().S(` `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:7
	qw422016.E().S(field.Default)
//line ../../infrastructure/db/migrate/alter_table.qtpl:7
	qw422016.N().S(`;

`)
//line ../../infrastructure/db/migrate/alter_table.qtpl:9
	if field.Constraint.Index {
//line ../../infrastructure/db/migrate/alter_table.qtpl:9
		qw422016.N().S(`
    create `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
		if field.Constraint.Unique {
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
			qw422016.N().S(`unique `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
		}
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
		qw422016.N().S(`index `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
		qw422016.E().S(field.Table.Name)
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
		qw422016.N().S(`_`)
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
		qw422016.E().S(field.Constraint.Field.Name)
//line ../../infrastructure/db/migrate/alter_table.qtpl:10
		qw422016.N().S(`_idx
     on `)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
		qw422016.E().S(field.Table.Name)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
		qw422016.N().S(` (`)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
		qw422016.E().S(field.Constraint.Field.Name)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
		qw422016.N().S(`);`)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	}
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
}

//line ../../infrastructure/db/migrate/alter_table.qtpl:11
func WriteAlterTable(qq422016 qtio422016.Writer, field scanner.Field) {
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	StreamAlterTable(qw422016, field)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
}

//line ../../infrastructure/db/migrate/alter_table.qtpl:11
func AlterTable(field scanner.Field) string {
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	WriteAlterTable(qb422016, field)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	qs422016 := string(qb422016.B)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
	return qs422016
//line ../../infrastructure/db/migrate/alter_table.qtpl:11
}
